spring:
  output.ansi.enabled: ALWAYS
  application:
    name: ecommerce-services
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nashtech_ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PW:postgresql}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

fe-server:
  url: ${FE_URL:http://localhost:3000}

openapi:
  service:
    api-docs: ecommerce-service
    title: Ecommerce-service API Documentation
    version: ${API_DOC_VERSION:v0.0.1}
    server: ${BE_URL:http://localhost:8080}